// Created by iWeb 3.0.4 local-build-20260420

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,30),url:'Home_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Home_files/stroke_1.png'},{rect:new IWRect(1,-1,968,2),url:'Home_files/stroke_2.png'},{rect:new IWRect(969,-1,2,2),url:'Home_files/stroke_3.png'},{rect:new IWRect(969,1,2,30),url:'Home_files/stroke_4.png'},{rect:new IWRect(969,31,2,2),url:'Home_files/stroke_5.png'},{rect:new IWRect(1,31,968,2),url:'Home_files/stroke_6.png'},{rect:new IWRect(-1,31,2,2),url:'Home_files/stroke_7.png'}],new IWSize(970,32)),stroke_2:new IWStrokeParts([{rect:new IWRect(-4,4,8,300),url:'Home_files/stroke_8.png'},{rect:new IWRect(-4,-4,8,8),url:'Home_files/stroke_9.png'},{rect:new IWRect(4,-4,327,8),url:'Home_files/stroke_10.png'},{rect:new IWRect(331,-4,8,8),url:'Home_files/stroke_11.png'},{rect:new IWRect(331,4,8,300),url:'Home_files/stroke_12.png'},{rect:new IWRect(331,304,8,8),url:'Home_files/stroke_13.png'},{rect:new IWRect(4,304,327,8),url:'Home_files/stroke_14.png'},{rect:new IWRect(-4,304,8,8),url:'Home_files/stroke_15.png'}],new IWSize(335,308))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Home_files/HomeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
