# Generated by Django 4.2.30 on 2026-05-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('project_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Project Inquiry',
                'verbose_name_plural': 'Project Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
