# Generated by Django 4.2.30 on 2026-04-30 23:42

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('template', models.CharField(choices=[('hero', 'Hero'), ('spotlight', 'Spotlight'), ('card', 'Card'), ('ribbon', 'Ribbon'), ('image_banner', 'Image Banner')], default='hero', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured_home', models.BooleanField(default=False, help_text='Show on home page')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='promotions/hero/')),
                ('hero_image_focal_y', models.FloatField(default=0.5)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='promotions/mobile/')),
                ('mobile_image_focal_y', models.FloatField(default=0.5)),
                ('image_no_crop', models.BooleanField(default=False)),
                ('bg_color', colorfield.fields.ColorField(default='#1a1a1a', image_field=None, max_length=25, samples=None)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('body_text', models.TextField(blank=True)),
                ('cta_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, default='Shop Now', max_length=80)),
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Promotion Page',
                'verbose_name_plural': 'Promotion Pages',
            },
        ),
        migrations.CreateModel(
            name='PromotionCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='primary', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta_buttons', to='promotions.promotionpage')),
            ],
            options={
                'verbose_name': 'Promotion CTA',
                'verbose_name_plural': 'Promotion CTAs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PromotionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('heading', 'Heading'), ('divider', 'Divider'), ('spacer', 'Spacer')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/blocks/')),
                ('image_focal_y', models.FloatField(default=0.5)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='promotions.promotionpage')),
            ],
            options={
                'verbose_name': 'Promotion Block',
                'verbose_name_plural': 'Promotion Blocks',
                'ordering': ['sort_order'],
            },
        ),
    ]
