# Generated by Django 4.2.30 on 2026-05-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('before_screenshot', models.ImageField(blank=True, null=True, upload_to='before_after/before/')),
                ('after_screenshot', models.ImageField(blank=True, null=True, upload_to='before_after/after/')),
                ('before_label', models.CharField(default='Before', max_length=100)),
                ('after_label', models.CharField(default='After', max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Before/After Site',
                'verbose_name_plural': 'Before/After Sites',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('web_app', 'Web Application'), ('ecommerce', 'E-Commerce'), ('marketing', 'Marketing Site'), ('cms', 'Custom CMS')], default='marketing', max_length=30)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField(blank=True)),
                ('tech_stack', models.CharField(help_text='Comma-separated: Django, Python, Tailwind CSS', max_length=300)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['sort_order', '-year'],
            },
        ),
    ]
