# Generated by Django 4.2.30 on 2026-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeaftersite',
            name='after_url',
            field=models.URLField(blank=True, help_text='Live URL of the new site (must allow iframe embedding)'),
        ),
        migrations.AddField(
            model_name='beforeaftersite',
            name='before_url',
            field=models.URLField(blank=True, help_text="Wayback Machine embed URL — append 'if_/' before the original URL, e.g. https://web.archive.org/web/20200101if_/http://example.com"),
        ),
        migrations.AddField(
            model_name='beforeaftersite',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
