# Generated by Django 4.2.30 on 2026-05-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_beforeaftersite_after_url_beforeaftersite_before_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OOSBlurb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tweet', 'Tweet (X / Twitter)'), ('email', 'Email'), ('sms', 'SMS / iMessage'), ('review', 'Google Review'), ('yelp', 'Yelp Review'), ('instagram', 'Instagram')], max_length=12)),
                ('sentiment', models.CharField(choices=[('bad', 'Bad (negative)'), ('good', 'Good (positive)')], max_length=4)),
                ('light_mode', models.BooleanField(default=False, help_text='Use light card background instead of dark')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('live_dur', models.FloatField(default=5.0, help_text='Post-reveal loop duration in seconds (e.g. 4.5)')),
                ('live_delay', models.FloatField(default=0.0, help_text='Post-reveal loop start delay in seconds (e.g. 1.4)')),
                ('author_name', models.CharField(blank=True, max_length=80)),
                ('author_handle', models.CharField(blank=True, help_text='Include @, e.g. @sarah_chen', max_length=80)),
                ('avatar_color', models.CharField(blank=True, help_text='CSS colour, e.g. #e07060', max_length=20)),
                ('from_email', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('sms_1_dir', models.CharField(blank=True, choices=[('in', 'In (received)'), ('out', 'Out (sent)')], max_length=3)),
                ('sms_1_text', models.CharField(blank=True, max_length=200)),
                ('sms_2_dir', models.CharField(blank=True, choices=[('in', 'In (received)'), ('out', 'Out (sent)')], max_length=3)),
                ('sms_2_text', models.CharField(blank=True, max_length=200)),
                ('sms_3_dir', models.CharField(blank=True, choices=[('in', 'In (received)'), ('out', 'Out (sent)')], max_length=3)),
                ('sms_3_text', models.CharField(blank=True, max_length=200)),
                ('star_count', models.PositiveSmallIntegerField(default=5, help_text='1–5 stars')),
                ('reviewer_label', models.CharField(blank=True, help_text='e.g. "Google Review, 2024"', max_length=120)),
                ('ig_username', models.CharField(blank=True, help_text='e.g. @their_business', max_length=80)),
                ('ig_followers', models.CharField(blank=True, help_text='Display string, e.g. 4,821 followers', max_length=40)),
                ('ig_likes', models.CharField(blank=True, help_text='Display string, e.g. 847 likes', max_length=40)),
                ('body_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'OOS Blurb',
                'verbose_name_plural': 'OOS Blurbs',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
