# Generated by Django 4.2.30 on 2026-07-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_oos_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_app', 'Web Application'), ('ecommerce', 'E-Commerce'), ('marketing', 'Marketing Site'), ('cms', 'Custom CMS'), ('research', 'Research & Product'), ('craft', 'Hands-On / Craft')], default='marketing', max_length=30),
        ),
    ]
