# Generated by Django 4.2.30 on 2026-07-02 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home_fact', 'Home — Quick Facts'), ('achievement', 'Music — Notable Achievements'), ('repertoire', 'Music — Repertoire & Influences')], max_length=20)),
                ('title', models.CharField(help_text='Fact text / achievement headline / composer name', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Venue-year / piece title', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Optional note or description')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'List Item',
                'verbose_name_plural': 'List Items (facts / achievements / repertoire)',
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_hero_name', models.CharField(default='Shwetanshu', max_length=100)),
                ('home_about_eyebrow', models.CharField(default='About me', max_length=100)),
                ('home_about_heading', models.TextField(default='A pianist,\na developer,\nand a lot more.', help_text='One line per line break — rendered with line breaks preserved.')),
                ('home_cta_heading', models.CharField(default='Want to work together?', max_length=200)),
                ('webdev_hero_eyebrow', models.CharField(default='Full-stack · Django & Python · Production deployments', max_length=200)),
                ('webdev_hero_title', models.CharField(default='Websites that work.', max_length=200)),
                ('webdev_hero_tagline', models.TextField(default='I design, build, and host Django sites for local businesses — no page builders, no templates. Every client owns a real admin panel and a site that actually ranks.')),
                ('webdev_response_caption', models.CharField(default='Shwetanshu responding to a client email, wherever he happens to be.', max_length=200)),
                ('webdev_cta_heading', models.CharField(default='Ready to build something?', max_length=200)),
                ('webdev_cta_text', models.CharField(default="Tell me what you need. I'll give you an honest scope and timeline.", max_length=300)),
                ('music_intro', models.TextField(default='Started at seven. Trained through the Royal Conservatory of Music — Bach, Chopin, Mozart, Beethoven, Schubert. Still playing.')),
                ('music_achievements_eyebrow', models.CharField(default='Notable achievements', max_length=100)),
                ('music_achievements_heading', models.CharField(default='On the record', max_length=200)),
                ('music_acoustics_text', models.TextField(default='A thank-you to my teacher, Dr. Michael Lehtinen (Eastman, Oberlin): a friend and I are building and installing Rockwool acoustic treatment for the recital hall where I trained. Unpaid, still in progress.')),
                ('music_cta_heading', models.CharField(default='Want to talk about a website?', max_length=200)),
                ('music_cta_text', models.CharField(default='The music is personal. The web work is how I earn — and I take it just as seriously.', max_length=300)),
                ('projects_hero_title', models.CharField(default='Projects', max_length=200)),
                ('projects_hero_subtitle', models.CharField(default="Client sites, a research build, and one project nobody's paying me for.", max_length=300)),
                ('projects_cta_heading', models.CharField(default='Want a site like one of these?', max_length=200)),
                ('ba_hero_title', models.CharField(default='Same business, new site', max_length=200)),
                ('ba_hero_subtitle', models.CharField(default="Drag the slider to compare what was there before against what's live now.", max_length=300)),
                ('contact_hero_title', models.CharField(default="Let's Build Something Together", max_length=200)),
                ('contact_intro', models.TextField(default="Whether you need a brand new website, a redesign, or a custom web application — I'd love to hear about it. I work directly with business owners, no middlemen.")),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Photo',
                'verbose_name_plural': 'Project Photos',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
