# Generated by Django 4.2.30 on 2026-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_listitem_sitecontent_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional — makes the photo clickable, e.g. a live search result or source page.'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='projects_hero_subtitle',
            field=models.CharField(default="Client sites, a research build, and a couple projects that aren't even done yet.", max_length=300),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='projects_hero_title',
            field=models.CharField(default="A few things I'm excited to show", max_length=200),
        ),
    ]
