# Generated by Django 4.2.30 on 2026-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projectimage_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeaftersite',
            name='visit_url',
            field=models.URLField(blank=True, help_text='Live URL to link to when the after-side is a static screenshot (not embedded as an iframe). Makes the after panel clickable without the slow/unreliable live-iframe load.'),
        ),
    ]
