# Generated by Django 4.2.30 on 2026-07-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_beforeaftersite_visit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='related_search_queries',
            field=models.CharField(blank=True, help_text='Comma-separated search queries that also rank #1 for this site. Each renders as a small chip that opens a live Google search in a new tab.', max_length=500),
        ),
    ]
