# Generated by Django 4.2.30 on 2026-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_projectimage_related_search_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeaftersite',
            name='after_year',
            field=models.CharField(blank=True, help_text='e.g. 2026 — shown next to the After label', max_length=20),
        ),
        migrations.AddField(
            model_name='beforeaftersite',
            name='before_year',
            field=models.CharField(blank=True, help_text='e.g. 2009 — shown next to the Before label', max_length=20),
        ),
    ]
