# Generated by Django 4.2.30 on 2026-07-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_beforeaftersite_after_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paper_file',
            field=models.FileField(blank=True, help_text='Optional PDF — e.g. a research paper or writeup related to this project.', null=True, upload_to='projects/papers/'),
        ),
    ]
